### ISSUE TITLE
add feature 

### ISSUE THREAD

**Issue by friktiny** [SpreeHertz/Cleckzie#16]
can you add phone feature and global chat feature ?

**Comment by SpreeHertz** [comment]
I'll try. Need to update some stuff first, and isn't the "phone feature" the same thing as the "global chat" feature? 
In the **phone command**, a user in Server A can talk to another user in Server B, isn't it?

**Comment by friktiny** [comment]
yes

**Comment by SpreeHertz** [comment]
I appreciate your suggestions, but this is not an issue. Next time, please use the Discussions feature (maybe go to the Ideas section) and suggest. 

Thank you.
